name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build App
        run: yarn build
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:     
          parent: false
          path: 'build'
          destination: 'cado.gooddev.app'